export const ServicesJson = [
  {
      id: 1,
      className: 'curriculum-design',
      classNameItem: 'item-1',
      title: 'Curriculum Design',
      definition: 'Planning and developing educational experiences that align with learning goals.',
      imageUrl: 'curriculum-design-images',
      description: `"Crafting innovative curricula tailored to educational needs. Enhancing student engagement and learning outcomes."`,
  },
  {
      id: 2,
      className: 'finish-curriculum',
      classNameItem: 'item-2',
      title: 'Finish Curriculum',
      definition: 'Completing and refining existing curricula for educational institutions.',
      imageUrl: 'finish-curriculum-images',
      description: `"Supporting curriculum completion and refinement. Ensuring readiness for implementation."`,
  },
  {
      id: 3,
      className: 'eary-child-development-3',
      classNameItem: 'item-3',
      title: 'Early Child Development',
      definition: 'Promoting growth in cognitive, physical, social, and emotional skills for children.',
      imageUrl: 'eary-child-development-images',
      description: `"Creating nurturing environments for young learners. Supporting holistic development."`,
  },
  {
      id: 4,
      className: 'class-room-management-4',
      classNameItem: 'item-4',
      title: 'Class Room Management',
      definition: 'Strategies for creating positive and productive learning environments.',
      imageUrl: 'class-room-management-images',
      description: `"Providing tools for positive classroom dynamics. Enhancing student engagement."`,
  },
  {
      id: 5,
      className: 'accelarated-learning-5',
      classNameItem: 'item-5',
      title: 'Accelerated Learning',
      definition: 'Optimizing learning processes for faster and effective knowledge absorption.',
      imageUrl: 'accelarated-learning-images',
      description: `"Enhancing retention, comprehension, and application of information. Paving the way for accelerated progress."`,
  },
  {
      id: 6,
      className: 'problem-based-learning-6',
      classNameItem: 'item-6',
      title: 'Problem Based Learning',
      definition: 'Engaging students in real-world problem-solving and collaboration.',
      imageUrl: 'problem-based-learning-images',
      description: `"Fostering critical thinking and collaboration. Designing PBL modules for lifelong learning."`,
  },
  {
      id: 7,
      className: 'active-learning-7',
      classNameItem: 'item-7',
      title: 'Active Learning',
      definition: 'Encouraging students to actively engage in the learning process.',
      imageUrl: 'active-learning-images',
      description: `"Promoting deeper understanding through active exploration and discussion. Creating dynamic learning environments."`,
  },
];
